# Numpy In Python


## What is Numpy ?


**NumPy** is a Python library used for numerical computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays efficiently.

## What is Numpy Array ?

A **NumPy array** is a grid of values, all of the same type, indexed by a tuple of non-negative integers. It is similar to a Python list but is more powerful because it supports efficient operations and broadcasting, allowing for element-wise computations.


## Type of Numpy Array


1. **1D Array (Vector)**: A single-dimensional array, similar to a list.
2. **2D Array (Matrix)**: A two-dimensional array, like a table of rows and columns.
3. **3D Array (Tensor)**: A multi-dimensional array with three or more dimensio
4. **Multi Dimentional**ns.


## Numpy VS Python List

*Advantanges of Numpy*

1. Numpy consumes less memory
2. Numpy is fast
3. Numpy is convenient to use
   

## Installation

In [48]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


## Import

In [52]:
import numpy as np

## Imporatance of numpy in python


1. Wide varity of Mathematical operations
2. it supplies enormous library of high mathematical functions

## Difference between Numpy and Python List



1. **Performance**: NumPy arrays are faster and more efficient than Python lists due to their fixed type and optimized operations.
2. **Memory Usage**: NumPy arrays consume less memory compared to Python lists.
3. **Functional Capabilities**: NumPy supports vectorized operations, allowing for element-wise computations without loops, whereas Python lists require iteration.
4. **Data Type**: All elements in a NumPy array must be of the same type, while Python lists can hold mixed data types.
5. **Built-in Methods**: NumPy has numerous built-in mathematical functions for arrays, which are not available for Python lists.


## Creating Numpy Array

In [73]:
var = np.array([1,2,3,4])
print(var)

[1 2 3 4]


## Dimentions in Array

In [81]:
# 1-d Array
a = np.array([1,2,3,4])
print(a)
print(a.ndim)

[1 2 3 4]
1


In [93]:
#2-D Array
b = np.array([[1,2,3,4],[1,2,3,4]])
print(b)
print(b.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


In [95]:
#3-D Array
c = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(c)
print(c.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


In [97]:
#To create Multi dimentional array use np.array(data,ndmin= value)
d = np.array([1,2,3,4],ndmin=10)
print(d)
print(d.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


## Create Numpy array using numpy function

**Zeros**

In [107]:

# 1-D
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [109]:
#2-D
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


**Ones**


In [112]:
#1-D
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [114]:
#2-D 
x= np.ones((2,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [116]:
x= np.ones((3,2))
print(x)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


**Empty**


In [119]:
x= np.empty(4)
print(x)

[6.23042070e-307 4.67296746e-307 1.69121096e-306 7.56602523e-307]


**Dignoal element filled with 1**

In [122]:
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [124]:
x = np.eye(3,5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


**line Space**


In [127]:
x = np.linspace(0,20,5)
print(x)

[ 0.  5. 10. 15. 20.]


## Creating numpy array with random number

1.rand()

In [134]:
x = np.random.rand(5)
print(x)

[0.16901238 0.51060926 0.17321742 0.32850384 0.9138102 ]


2.randn()

In [140]:
x = np.random.randn(5)
print(x)

[-0.29916241 -1.06984905  0.70480472  1.59897942  0.00992114]


3. ranf()
   

In [143]:
x = np.random.ranf(5)
print(x)

[0.08130097 0.08796921 0.92051491 0.15419219 0.00805272]


4. randint()

In [152]:
x = np.random.randint(1, 20, 5)
print(x)


[19 17 10  7 10]


## Data Types in NumPy Arrays
e=np.float64)


NumPy arrays can store elements of a specific data type. The type of data in an array is called `dtype`. Some common NumPy data types include:

1. **int**: Integer types (e.g., `np.int32`, `np.int64`)
2. **float**: Floating point numbers (e.g., `np.float32`, `np.float64`)
3. **complex**: Complex numbers (e.g., `np.complex64`, `np.complex128`)
4. **bool**: Boolean values (`True` or `False`)
5. **str**: String data type (e.g., `np.str_`)

You can specify the data type when creating a NumPy array by using the `dtype` parameter:

```python
arr = np.array([1, 2, 3], dtype=np.float64)

**To find Data Type**

In [161]:
x = np.array([1,2,3,4])
print(x.dtype)

int32


## Arithmetic Operations

In [167]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

#### Addition

In [176]:
print(a+b)

[2 4 6 8]


In [178]:
print(np.add(a,b))

[2 4 6 8]


#### Subtraction


In [180]:
print(a-b)

[0 0 0 0]


In [182]:
print(np.subtract(a,b))

[0 0 0 0]


#### Multiply

In [186]:
print(a*b)

[ 1  4  9 16]


In [190]:
print(np.multiply(a,b))

[ 1  4  9 16]


#### Divide

In [194]:
print(a/b)

[1. 1. 1. 1.]


In [199]:
print(np.divide(a,b))

[1. 1. 1. 1.]


#### Mod

In [203]:
print(a%b)

[0 0 0 0]


In [207]:
print(np.mod(a,b))

[0 0 0 0]


#### power

In [215]:
print(a**b)

[  1   4  27 256]


In [217]:
print(np.power(a,b))

[  1   4  27 256]


#### Reciprocal

In [236]:
print(1/a)

[1.         0.5        0.33333333 0.25      ]


In [232]:
print(np.reciprocal(a))

[1 0 0 0]


## Arithmetic Function

In [241]:
x= np.array([2,5,4,7,8,9,2,5,6,10,12,13])

**Max**

In [244]:
print(np.max(x))

13


**min**

In [247]:
print(np.min(x))

2


**Argmin/argmax**

In [256]:
print(np.argmin(x))

0


In [258]:
print(np.argmax(x))

11


**Squre Root**

In [261]:
print(np.sqrt(x))

[1.41421356 2.23606798 2.         2.64575131 2.82842712 3.
 1.41421356 2.23606798 2.44948974 3.16227766 3.46410162 3.60555128]


**Sin**


In [267]:
print(np.sin(x))

[ 0.90929743 -0.95892427 -0.7568025   0.6569866   0.98935825  0.41211849
  0.90929743 -0.95892427 -0.2794155  -0.54402111 -0.53657292  0.42016704]


**cos**


In [269]:

print(np.cos(x))

[-0.41614684  0.28366219 -0.65364362  0.75390225 -0.14550003 -0.91113026
 -0.41614684  0.28366219  0.96017029 -0.83907153  0.84385396  0.90744678]


**Cumsum**

In [271]:
print(np.cumsum(x))

[ 2  7 11 18 26 35 37 42 48 58 70 83]


## Shape & Reshape

#### Shape

In [28]:
import numpy as np
x = np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [30]:
print(x.shape)

(2, 2)


In [34]:
y = np.array([1,2, 3,4],ndmin = 4)
y
print(y.shape)

(1, 1, 1, 4)


#### Reshape

In [43]:
x = np.array([1,2,3,4,5,6,7,8])
y = x.reshape(4,2)
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## Broad casting

- Should have same dimensions
- Both should have 1 from left hand side

## Indexing

#### 1-D

In [50]:
import numpy as np
x = np.array([1,2,3,4])
#             0 1 2 3

In [52]:
print(x[2])

3


#### 2-D

In [70]:
import numpy as np
x = np.array([[1,2],[3,4]])       
x

array([[1, 2],
       [3, 4]])

In [72]:
#     0  1 
# 0 [[1, 2],
# 1  [3, 4]])

print(x[0,0])

1


In [74]:
print(x[0,1])

2


#### 3-D

In [80]:
import numpy as np
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])       
print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [82]:
#     0 1
# [ [[1 2]0
#    [3 4]1]0
#   [[5 6]0
#    [7 8]1]1 ]  

In [84]:
print(x[1,0,1])

6


## Slicing

In [88]:
import numpy as np
x = np.array([1,2,3,4,5])
print(x)


[1 2 3 4 5]


In [90]:
print(x[0:])

[1 2 3 4 5]


In [92]:
print(x[0:3])

[1 2 3]


In [94]:
print(x[3:])

[4 5]


## Iterating Numpy array

#### method 1

##### 1-D

In [99]:
import numpy as np

x = np.array([1,2,3,4,5,6,7,8,9])
print(x)

[1 2 3 4 5 6 7 8 9]


In [101]:
for i in x:
    print(i)

1
2
3
4
5
6
7
8
9


##### 2-D


In [112]:
import numpy as np

x = np.array([[1,2,3,4],[5,6,7,8]])
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [120]:
for i in x:
    print(x)
#False Result

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [122]:
for i in x:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8


##### 3-D

In [124]:
import numpy as np
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])       
print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [126]:
for i in x:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
6
7
8


#### Method 2

In [129]:
import numpy as np
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])       
print(x)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [133]:
for i in np.nditer(x):
    print(i)

1
2
3
4
5
6
7
8


In [139]:
# for Index
for i,d  in np.ndenumerate(x):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


## Copy VS View 

#### Copy

- **Definition**: A copy is an entirely new array or DataFrame that replicates the data of the original. Any modifications to the copied object do not affect the original.

In [7]:
import numpy as np
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])       
print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [144]:
var = x.copy()

In [146]:
print(var)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
a = np.array([1,2,3,4])
print(a)
print()
b = a.copy()
print(b)
print()

a[2] = 30
print(a)
print()
print(b)

[1 2 3 4]

[1 2 3 4]

[ 1  2 30  4]

[1 2 3 4]


#### View

- **Definition**: A view is a new object that shares the same data as the original array or DataFrame. Any modifications made to the view will affect the original and vice versa.

In [150]:
import numpy as np
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])       
print(x)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [152]:
var2 = x.view()

In [154]:
print(var2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [29]:
a = np.array([1,2,3,4])
print(a)
print()
b = a.view()
print(b)
print()

a[2] = 30
print(a)
print()
print(b)

[1 2 3 4]

[1 2 3 4]

[ 1  2 30  4]

[ 1  2 30  4]


## Join & Split Funtion

- **Join Array**: Joining means putting content of two or more array in single one.

### Concatenate

#### 1-D

In [40]:
a = np.array([1,2,3,4])
print(a)
b = np.array([5,6,7,8])
print(b)
c = np.concatenate((a,b))
print(c)

[1 2 3 4]
[5 6 7 8]
[1 2 3 4 5 6 7 8]


#### 2-D

In [47]:
a = np.array([[1,2],[3,4]])
print(a)
print()
b = np.array([[5,6],[7,8]])
print(b)
print()
c = np.concatenate((a,b), axis = 1)
print(c)


[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [49]:
a = np.array([[1,2],[3,4]])
print(a)
print()
b = np.array([[5,6],[7,8]])
print(b)
print()
c = np.concatenate((a,b), axis = 0)
print(c)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Stack

In [69]:
a = np.array([1,2,3,4])
print(a)
print()
b = np.array([5,6,7,8])
print(b)
print()
c = np.stack((a,b),axis = 0)
print(c)
print()
d = np.stack((a,b),axis = 1)
print(d)
print()
e = np.hstack((a,b))
print(e)
print()
f = np.vstack((a,b))
print(f)
print()
g = np.dstack((a,b))
print(g)
print()


[1 2 3 4]

[5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]



### Split

- Spliting breaks one array into multiple

In [77]:
a = np.array([1,2,3,4,5,6,7,8])
print(a)


[1 2 3 4 5 6 7 8]


In [81]:
b = np.array_split(a,3)
print(b)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [83]:
c = np.array_split(a,2)
print(c)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


## Numpy Array Functions

In [94]:
x= np.array([1,2,3,4,2,14,45,56,54,78,83,12, 3, 4, 2])
#            0 1 2 3 4 5  6  7   8  9 10 11 12 13 14

### Search

In [90]:
a = np.where(x == 2)
print(a)

(array([ 1,  4, 14], dtype=int64),)


### Search Sorted Array

In [137]:
g = np.array([1,2,3,4,6,7,8,9,10])

In [139]:
a = np.searchsorted(g, 5)
print(a)


4


In [141]:
B = np.searchsorted(g, 5, side= "right")
print(B)

4


### Sort Array

In [146]:
x = np.array([3,5,2,34,75,3,7,89,6,5])
print(x)
print()
y = np.sort(x)
print(y)

[ 3  5  2 34 75  3  7 89  6  5]

[ 2  3  3  5  5  6  7 34 75 89]


### Filter Array

In [155]:
e = np.array([1,2,3,4])
f= [True,False,False,True]
print(e[f])

[1 4]


### Shuffle

In [168]:
x = np.array([1,2,3,4,5,6,7,8,9])


In [176]:
np.random.shuffle(x)
print(x)

[7 5 8 2 9 1 3 4 6]


### Unique

In [180]:
x= np.array([1,2,3,4,2,14,45,56,54,78,83,12, 3, 4, 2])

In [186]:
y = np.unique(x)
print(y)

[ 1  2  3  4 12 14 45 54 56 78 83]


In [188]:
z = np.unique(x, return_index = True)
print(z)

(array([ 1,  2,  3,  4, 12, 14, 45, 54, 56, 78, 83]), array([ 0,  1,  2,  3, 11,  5,  6,  8,  7,  9, 10], dtype=int64))


In [194]:
f = np.unique(x, return_index = True, return_counts = True)
print(f)

(array([ 1,  2,  3,  4, 12, 14, 45, 54, 56, 78, 83]), array([ 0,  1,  2,  3, 11,  5,  6,  8,  7,  9, 10], dtype=int64), array([1, 3, 2, 2, 1, 1, 1, 1, 1, 1, 1], dtype=int64))


### Resize

In [196]:
x = np.array([1,2,3,4,5,6,7,8])


In [198]:
y= np.resize(x,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [200]:
z= np.resize(x,(3,2))
print(z)

[[1 2]
 [3 4]
 [5 6]]


### Flatten & Ravel

In [204]:
x = np.array([[1,2,3,4],[5,6,7,8]])
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [211]:
z= np.resize(x,(3,2))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [215]:
print("Flatten : ", z.flatten())

Flatten :  [1 2 3 4 5 6]


In [225]:
print("Ravel : ", np.ravel(z))

Ravel :  [1 2 3 4 5 6]


### Insert

#### 1-D

In [231]:
n = np.array([1,2,3,5,6,7,8])
print(n)

[1 2 3 5 6 7 8]


In [ ]:
# Insert Function

In [241]:
a = np.insert(n,3,4)
print(a)

[1 2 3 4 5 6 7 8]


In [ ]:
# Append Funtion

In [244]:
b = np.append(n,4)
print(b)

[1 2 3 5 6 7 8 4]


#### 2-D

In [252]:
n = np.array([[1,2,3,4],[5,6,7,8]])
print(n)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# Insert Function

In [254]:
a = np.insert(n,1,10,0)
print(a)

[[ 1  2  3  4]
 [10 10 10 10]
 [ 5  6  7  8]]


In [256]:
b = np.insert(n,1,10,1)
print(b)

[[ 1 10  2  3  4]
 [ 5 10  6  7  8]]


In [258]:
# Append Function

In [278]:
c = np.append(n,[[10,10,1,2]],axis = 0)
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 10  1  2]]


In [282]:
f = np.append(n,[[1],[2]],axis = 1)
print(f)

[[1 2 3 4 1]
 [5 6 7 8 2]]


### Delete

In [285]:
x = np.array([1,2,3,4,5,5,6,7,8])

In [297]:
print(x)
print(len(x))

[1 2 3 4 5 5 6 7 8]
9


In [301]:
y = np.delete(x,4)
print(y)
print(len(y))

[1 2 3 4 5 6 7 8]
8
